fff-gateway: provide specific error if config version is not set
This explicitly checks whether the config version is set at all,
instead of just comparing it, and provides a specific error message
for that case.

Signed-off-by: Adrian Schmutzler <freifunk@adrianschmutzler.de>
Reviewed-by: Robert Langhammer <rlanghammer@web.de>
Reviewed-by: Fabian Bläse <fabian@blaese.de>

diff --git a/src/packages/fff/fff-gateway/files/etc/gateway.d/01-version b/src/packages/fff/fff-gateway/files/etc/gateway.d/01-version
--- a/src/packages/fff/fff-gateway/files/etc/gateway.d/01-version
+++ b/src/packages/fff/fff-gateway/files/etc/gateway.d/01-version
@@ -10,6 +10,12 @@ configure() {
 	fi
 
 	# check version of configuration
+	if ! [ -n "$config_version" ]; then
+		echo "ERROR: No config version given. Supported versions: '$expected_version'"
+
+		exit 1
+	fi
+
 	if [ "$config_version" != "$expected_version" ]; then
 		echo "ERROR: Invalid config version. Expected '$expected_version', got '$config_version'."
 		echo "Please check what has been changed and adjust your config appropriately."
