buildscript: add color to the root warning
Use color output when the `tput` command is available.
`tput` handles terminal-dependant capabilities, so the script should
remain portable.

Signed-off-by: Johannes Kimmel <fff@bareminimum.eu>
Reviewed-by: Fabian Bläse <fabian@blaese.de>

diff --git a/buildscript b/buildscript
--- a/buildscript
+++ b/buildscript
@@ -381,8 +381,12 @@ buildall() {
 }
 
 if [ "$(/usr/bin/id -u)" -eq 0 ]; then
-    echo "WARNING: buildscript is running as root"
-    echo "WARNING: build may fail at a later stage"
+    TPUT=$(command -v tput || echo ":")
+    textWarn="$($TPUT bold setaf 1)" # bold + red
+    textReset="$($TPUT sgr0)"        # be a good citizen
+
+    printf "${textWarn}WARNING: buildscript is running as root${textReset}\n"
+    printf "${textWarn}WARNING: build may fail at a later stage${textReset}\n"
 fi
 
 if [ "$1" != "selectbsp" -a "$1" != "selectvariant" ]; then
