bird: expose babel interface "limit" option
By default bird considers neighbors to be up when 12 or more HELLO
packets within a window of 16 are received.

This poses an issue on routers with a single uplink that suffers from
either frequent intermittend connection losses or firmware issues that
drops multicast packets.

Bird (or babel in general) will consider these links to be down
frequently, causing routing updates to the whole network and a complete
outage for the router behind the problematic link for a longer time than
necessary.

The wireless type can help in these situation, but there is no real
benefit from the constantly changing costs.

Therefore expose the limit option to the user, so a very low value may
be set on problematic links.

Signed-off-by: Johannes Kimmel <fff@bareminimum.eu>
Reviewed-by: Fabian Bläse <fabian@blaese.de>

diff --git a/src/packages/fff/fff-babel/files/etc/layer3.d/40-babel b/src/packages/fff/fff-babel/files/etc/layer3.d/40-babel
--- a/src/packages/fff/fff-babel/files/etc/layer3.d/40-babel
+++ b/src/packages/fff/fff-babel/files/etc/layer3.d/40-babel
@@ -35,7 +35,11 @@ configure() {
 		local prefixname="babelpeer_$name"
 		local vlan
 		local iface
+
+		# protocol options
 		local type
+		local rxcost
+		local limit
 
 		# get iface
 		if vlan=$(uci -q get gateway.$name.vlan); then
@@ -53,6 +57,12 @@ configure() {
 		# get rxcost
 		rxcost=$(uci -q get gateway.$name.rxcost) || rxcost=96
 
+		# get limit
+		# > how many of last 16 hellos have to be correctly received
+		# > in order to neighbor is assumed to be up
+		# babel_add_interface sets the default
+		limit=$(uci -q get gateway.$name.limit)
+
 		# add interface
 		uci set network.$prefixname=interface
 		uci set network.$prefixname.proto=static
@@ -68,7 +78,7 @@ configure() {
 		babel_add_peer6addr "network.$prefixname.ip6addr"
 
 		# add babel interface
-		babel_add_interface "$prefixname" "$iface" "$type" "$rxcost" || { echo "Could not add babel interface for babelpeer $name"; exit 1; }
+		babel_add_interface "$prefixname" "$iface" "$type" "$rxcost" "$limit" || { echo "Could not add babel interface for babelpeer $name"; exit 1; }
 	}
 
 	config_load gateway
